version: '3.9'

services:
  rust_runner:
    container_name: rust_runner
    image: rust_runner
    env_file:
      - "./secret_data.env"
    build:
      context: .
      dockerfile: ./rust_runner/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
      - rust_sign_up
      - rust_sign_in
      - rust_get_user_data
      - rust_put_del_user_data
      - rust_post_del_friend
    networks:
      - mynetwork

  db:
    container_name: db
    image: postgres:alpine
    # env_file:
    #   - "./secret_db.env"
    environment:
      POSTGRES_USER: secret_db_user
      POSTGRES_PASSWORD: secret_db_password
      POSTGRES_DB: rust_db
    ports:
      - '5436:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  rust_sign_up:
    container_name: rust_sign_up
    image: rust_sign_up
    env_file:
      - "./secret_data.env"
    build:
      context: .
      dockerfile: ./handle_signup_req/Dockerfile
    expose:
      - '5544'
    networks:
      - mynetwork

  rust_sign_in:
    container_name: rust_sign_in
    image: rust_sign_in
    env_file:
      - "./secret_data.env"
    build:
      context: .
      dockerfile: ./handle_signin_req/Dockerfile
    expose:
      - '5545'
    networks:
      - mynetwork

  rust_get_user_data:
    container_name: rust_get_user_data
    image: rust_get_user_data
    env_file:
      - "./secret_data.env"
    build:
      context: .
      dockerfile: ./handle_get_user_data_req/Dockerfile
    expose:
      - '5546'
    networks:
      - mynetwork

  rust_put_del_user_data:
    container_name: rust_put_del_user_data
    image: rust_put_del_user_data
    env_file:
      - "./secret_data.env"
    build:
      context: .
      dockerfile: ./handle_put_del_user_data_req/Dockerfile
    expose:
      - '5547'
    networks:
      - mynetwork

  rust_post_del_friend:
    container_name: rust_post_del_friend
    image: rust_post_del_friend
    env_file:
      - "./secret_data.env"
    build:
      context: .
      dockerfile: ./handle_post_del_friend_req/Dockerfile
    expose:
      - '5548'
    networks:
      - mynetwork

volumes:
  pgdata: {}

networks:
  mynetwork:
